layout_spectrum: 0.09703089250251651
typography_spectrum: 0.6223145467229187
color:
  brandStrength: 0.3562893436755985
  lightness: 0.8539226653520018
  saturation: 0.13775574089959264
  rhythmicContrast: 0.7067616416607052
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: E1
